"""empty message

Revision ID: 17934bcd193e
Revises: 3ada963056e6
Create Date: 2017-01-16 21:54:58.682783

"""

# revision identifiers, used by Alembic.
revision = '17934bcd193e'
down_revision = '3ada963056e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('sub_content', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'sub_content')
    # ### end Alembic commands ###
