"""empty message

Revision ID: 1a80cb60ea27
Revises: 51e766709a4f
Create Date: 2016-10-31 23:57:00.534122

"""

# revision identifiers, used by Alembic.
revision = '1a80cb60ea27'
down_revision = '51e766709a4f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('card_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'notification', 'card', ['card_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'card_id')
    ### end Alembic commands ###
