"""empty message

Revision ID: 200a09af5faa
Revises: bdebe8a99bbc
Create Date: 2016-10-21 23:22:40.707010

"""

# revision identifiers, used by Alembic.
revision = '200a09af5faa'
down_revision = 'bdebe8a99bbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('position', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'position')
    ### end Alembic commands ###
