"""empty message

Revision ID: 2d4673ad9843
Revises: a0cdf1353ee8
Create Date: 2016-10-29 00:57:15.595857

"""

# revision identifiers, used by Alembic.
revision = '2d4673ad9843'
down_revision = 'a0cdf1353ee8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_comments', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('card_comments', sa.Column('updated_at', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_comments', 'updated_at')
    op.drop_column('card_comments', 'created_at')
    ### end Alembic commands ###
