"""empty message

Revision ID: 3249063ecced
Revises: 90c85edfd74f
Create Date: 2016-10-30 20:13:59.984209

"""

# revision identifiers, used by Alembic.
revision = '3249063ecced'
down_revision = '90c85edfd74f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    ### end Alembic commands ###
