"""empty message

Revision ID: 329c9e995bc9
Revises: w0009
Create Date: 2017-01-05 20:58:03.048614

"""

# revision identifiers, used by Alembic.
revision = '329c9e995bc9'
down_revision = 'w0009'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('silver_points', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('card', 'prize_pool')
    op.add_column('transfer', sa.Column('silver_points', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('transfer', 'amount')
    op.add_column('user', sa.Column('silver_points', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('user', 'points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('points', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False))
    op.drop_column('user', 'silver_points')
    op.add_column('transfer', sa.Column('amount', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False))
    op.drop_column('transfer', 'silver_points')
    op.add_column('card', sa.Column('prize_pool', sa.INTEGER(), server_default=sa.text(u'0'), autoincrement=False, nullable=False))
    op.drop_column('card', 'silver_points')
    # ### end Alembic commands ###
