"""empty message

Revision ID: 3ada963056e6
Revises: f37f13500a4e
Create Date: 2017-01-07 21:24:14.904407

"""

# revision identifiers, used by Alembic.
revision = '3ada963056e6'
down_revision = 'f37f13500a4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tier', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tier')
    # ### end Alembic commands ###
