"""empty message

Revision ID: 4b3cec97458f
Revises: 2d4673ad9843
Create Date: 2016-10-29 01:28:37.396255

"""

# revision identifiers, used by Alembic.
revision = '4b3cec97458f'
down_revision = '2d4673ad9843'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'card_comments_user_id_fkey', 'card_comments', type_='foreignkey')
    op.drop_constraint(u'card_comments_card_id_fkey', 'card_comments', type_='foreignkey')
    op.drop_column('card_comments', 'user_id')
    op.drop_column('card_comments', 'card_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_comments', sa.Column('card_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('card_comments', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'card_comments_card_id_fkey', 'card_comments', 'card', ['card_id'], ['id'])
    op.create_foreign_key(u'card_comments_user_id_fkey', 'card_comments', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###
