"""empty message

Revision ID: 51e766709a4f
Revises: 96daf57dc695
Create Date: 2016-10-31 23:35:27.521904

"""

# revision identifiers, used by Alembic.
revision = '51e766709a4f'
down_revision = '96daf57dc695'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('extra_user_id', sa.String(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['extra_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    ### end Alembic commands ###
