"""empty message

Revision ID: 6814deee2174
Revises: c4195c894fcb
Create Date: 2017-03-08 20:15:29.246135

"""

# revision identifiers, used by Alembic.
revision = '6814deee2174'
down_revision = 'c4195c894fcb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmation_email', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('confirmation_email', sa.Column('year', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'confirmation_email', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'confirmation_email', type_='unique')
    op.drop_column('confirmation_email', 'year')
    op.drop_column('confirmation_email', 'username')
    ### end Alembic commands ###
