"""empty message

Revision ID: 6c71a659aee8
Revises: 4b3cec97458f
Create Date: 2016-10-29 01:28:49.490502

"""

# revision identifiers, used by Alembic.
revision = '6c71a659aee8'
down_revision = '4b3cec97458f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_comments', sa.Column('card_id', sa.String(), nullable=True))
    op.add_column('card_comments', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'card_comments', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'card_comments', 'card', ['card_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card_comments', type_='foreignkey')
    op.drop_constraint(None, 'card_comments', type_='foreignkey')
    op.drop_column('card_comments', 'user_id')
    op.drop_column('card_comments', 'card_id')
    ### end Alembic commands ###
