"""empty message

Revision ID: 90c85edfd74f
Revises: be19cd1f8bc0
Create Date: 2016-10-29 01:36:44.809979

"""

# revision identifiers, used by Alembic.
revision = '90c85edfd74f'
down_revision = 'be19cd1f8bc0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_comments',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'card_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_comments')
    ### end Alembic commands ###
