"""empty message

Revision ID: 96daf57dc695
Revises: 3249063ecced
Create Date: 2016-10-30 20:57:19.721468

"""

# revision identifiers, used by Alembic.
revision = '96daf57dc695'
down_revision = '3249063ecced'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bio')
    ### end Alembic commands ###
