"""answer_visibility add to card model

Revision ID: 9c86084b2cad
Revises: adff30e87615
Create Date: 2016-11-30 10:56:02.786000

"""

# revision identifiers, used by Alembic.
revision = '9c86084b2cad'
down_revision = 'adff30e87615'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('answer_visibility', sa.String(length=50), server_default='anyone', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'answer_visibility')
    ### end Alembic commands ###
