"""Fix autogeneration

Revision ID: a07979b6882f
Revises: 3ee083ba2c37
Create Date: 2016-11-25 09:30:38.987000

"""

# revision identifiers, used by Alembic.
revision = 'a07979b6882f'
down_revision = '3ee083ba2c37'

from alembic import op
import sqlalchemy as sa


def upgrade():
    update_fields()
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'format',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('card', 'is_ask_mode_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def update_fields():
    from lib.models.card import Card
    table = Card.__table__
    op.execute(
        table.update().values({'format':op.inline_literal(''), 'is_ask_mode_enabled': op.inline_literal(True)})
    )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'is_ask_mode_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('card', 'format',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###
