"""empty message

Revision ID: a0cdf1353ee8
Revises: 00279153ac9a
Create Date: 2016-10-29 00:55:00.612847

"""

# revision identifiers, used by Alembic.
revision = 'a0cdf1353ee8'
down_revision = '00279153ac9a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_comments',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'card_id')
    )
    op.drop_constraint(u'card_likes_card_id_fkey', 'card_likes', type_='foreignkey')
    op.drop_constraint(u'card_likes_user_id_fkey', 'card_likes', type_='foreignkey')
    op.create_foreign_key(None, 'card_likes', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'card_likes', 'card', ['card_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card_likes', type_='foreignkey')
    op.drop_constraint(None, 'card_likes', type_='foreignkey')
    op.create_foreign_key(u'card_likes_user_id_fkey', 'card_likes', 'user', ['user_id'], ['id'], ondelete=u'CASCADE')
    op.create_foreign_key(u'card_likes_card_id_fkey', 'card_likes', 'card', ['card_id'], ['id'], ondelete=u'CASCADE')
    op.drop_table('card_comments')
    ### end Alembic commands ###
