"""empty message

Revision ID: a20c595b5a5a
Revises: 67d312df2c02
Create Date: 2016-10-19 00:29:38.040034

"""

# revision identifiers, used by Alembic.
revision = 'a20c595b5a5a'
down_revision = '67d312df2c02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('description', sa.Text(), server_default='', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'description')
    ### end Alembic commands ###
