"""empty message

Revision ID: a8b5adabbb0d
Revises: 59578ffa9f14
Create Date: 2016-10-26 14:39:37.992439

"""

# revision identifiers, used by Alembic.
revision = 'a8b5adabbb0d'
down_revision = '59578ffa9f14'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('card', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('card', sa.Column('x_position', sa.Float(), nullable=True))
    op.add_column('card', sa.Column('y_position', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'y_position')
    op.drop_column('card', 'x_position')
    op.drop_column('card', 'width')
    op.drop_column('card', 'height')
    ### end Alembic commands ###
