"""empty message

Revision ID: bdebe8a99bbc
Revises: fd7950990fed
Create Date: 2016-10-21 23:18:49.978500

"""

# revision identifiers, used by Alembic.
revision = 'bdebe8a99bbc'
down_revision = 'fd7950990fed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_to_card')
    op.add_column('card', sa.Column('parent_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'card', 'card', ['parent_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'parent_id')
    op.create_table('card_to_card',
    sa.Column('parent_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['child_id'], [u'card.id'], name=u'card_to_card_child_id_fkey'),
    sa.ForeignKeyConstraint(['parent_id'], [u'card.id'], name=u'card_to_card_parent_id_fkey'),
    sa.PrimaryKeyConstraint('parent_id', 'child_id', name=u'card_to_card_pkey')
    )
    ### end Alembic commands ###
