"""empty message

Revision ID: be19cd1f8bc0
Revises: 6c71a659aee8
Create Date: 2016-10-29 01:35:36.420386

"""

# revision identifiers, used by Alembic.
revision = 'be19cd1f8bc0'
down_revision = '6c71a659aee8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_comments')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_comments',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('card_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], [u'card.id'], name=u'card_comments_card_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'card_comments_user_id_fkey')
    )
    ### end Alembic commands ###
