"""empty message

Revision ID: c4195c894fcb
Revises: w0018
Create Date: 2017-03-07 21:18:32.235559

"""

# revision identifiers, used by Alembic.
revision = 'c4195c894fcb'
down_revision = 'w0018'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmation_email',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('confirmation_code', sa.String(length=10), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmation_email')
    ### end Alembic commands ###
