"""empty message

Revision ID: edad351a6f72
Revises: 200a09af5faa
Create Date: 2016-10-25 22:10:32.374179

"""

# revision identifiers, used by Alembic.
revision = 'edad351a6f72'
down_revision = '200a09af5faa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('card', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('card', sa.Column('x_position', sa.Integer(), nullable=True))
    op.add_column('card', sa.Column('y_position', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'y_position')
    op.drop_column('card', 'x_position')
    op.drop_column('card', 'width')
    op.drop_column('card', 'height')
    ### end Alembic commands ###
