"""empty message

Revision ID: f37f13500a4e
Revises: 329c9e995bc9
Create Date: 2017-01-05 21:19:45.262322

"""

# revision identifiers, used by Alembic.
revision = 'f37f13500a4e'
down_revision = '329c9e995bc9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('gold_points', sa.Integer(), server_default='0', nullable=False))
    op.add_column('transfer', sa.Column('gold_points', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('gold_points', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gold_points')
    op.drop_column('transfer', 'gold_points')
    op.drop_column('card', 'gold_points')
    # ### end Alembic commands ###
