"""empty message

Revision ID: fd7950990fed
Revises: a20c595b5a5a
Create Date: 2016-10-21 21:58:55.116046

"""

# revision identifiers, used by Alembic.
revision = 'fd7950990fed'
down_revision = 'a20c595b5a5a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_to_card', sa.Column('position', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_to_card', 'position')
    ### end Alembic commands ###
