"""image_scale field for create_image_card endpoint

Revision ID: w0006
Revises: w0005
Create Date: 2016-12-12 13:28:10.031000

"""

# revision identifiers, used by Alembic.
revision = 'w0006'
down_revision = 'w0005'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('image_scale', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'image_scale')
    ### end Alembic commands ###
