"""Add card to transfer

Revision ID: w0009
Revises: w0008
Create Date: 2016-12-20 14:06:14.359000

"""

# revision identifiers, used by Alembic.
revision = 'w0009'
down_revision = 'w0008'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('card_from_id', sa.String(length=255), nullable=True))
    op.add_column('transfer', sa.Column('card_to_id', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'transfer', 'card', ['card_from_id'], ['id'])
    op.create_foreign_key(None, 'transfer', 'card', ['card_to_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.drop_column('transfer', 'card_to_id')
    op.drop_column('transfer', 'card_from_id')
    ### end Alembic commands ###
