"""Add card_tag relation

Revision ID: w0005
Revises: w0004
Create Date: 2016-12-10 10:36:29.601000

"""

# revision identifiers, used by Alembic.
revision = 'w0005'
down_revision = 'w0004'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'card_tag',
        sa.Column('card_id', sa.String(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_tag')
    ### end Alembic commands ###
