"""Scale field to card object

Revision ID: w0007
Revises: w0006
Create Date: 2016-12-17 09:59:52.051000

"""

# revision identifiers, used by Alembic.
revision = 'w0007'
down_revision = 'w0006'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('scale', sa.Integer(), nullable=True))
    op.drop_column('card', 'image_scale')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('image_scale', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('card', 'scale')
    ### end Alembic commands ###
