"""Add sub_comments to CardComment

Revision ID: w0010
Revises: 17934bcd193e
Create Date: 2017-01-28 20:23:52.643000

"""

# revision identifiers, used by Alembic.
revision = 'w0010'
down_revision = '17934bcd193e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('card_comments_pkey', 'card_comments', type_='primary')
    op.create_primary_key('pk_card_comments', 'card_comments', ['id'])
    op.add_column('card_comments', sa.Column('comment_id', sa.String(), nullable=True))
    op.alter_column('card_comments', 'card_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('card_comments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('uq_card_comments', 'card_comments', ['user_id', 'card_id', 'comment_id'])
    op.create_foreign_key('fk_sub_comments', 'card_comments', 'card_comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sub_comments', 'card_comments', type_='foreignkey')
    op.drop_constraint('uq_card_comments', 'card_comments', type_='unique')
    op.alter_column('card_comments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('card_comments', 'card_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('card_comments', 'comment_id')
    # ### end Alembic commands ###
