"""verification_code_for_user

Revision ID: w0017
Revises: w0016
Create Date: 2017-02-24 17:22:05.503000

"""

# revision identifiers, used by Alembic.
revision = 'w0017'
down_revision = 'w0016'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verification_code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_code')
    # ### end Alembic commands ###
