"""Add CommentLike entity

Revision ID: w0011
Revises: w0010
Create Date: 2017-01-30 23:30:25.429000

"""

# revision identifiers, used by Alembic.
revision = 'w0011'
down_revision = 'w0010'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_like',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['card_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_like')
    # ### end Alembic commands ###
