"""Add video_length to create_video_card

Revision ID: w0012
Revises: w0011
Create Date: 2017-01-31 21:53:19.842000

"""

# revision identifiers, used by Alembic.
revision = 'w0012'
down_revision = 'w0011'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('video_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'video_length')
    # ### end Alembic commands ###
