"""Add original_prize_pool to card

Revision ID: w0014
Revises: w0013
Create Date: 2017-02-06 12:16:18.321000

"""

# revision identifiers, used by Alembic.
revision = 'w0014'
down_revision = 'w0013'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('original_prize_pool', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'original_prize_pool')
    # ### end Alembic commands ###
